### ISSUE TITLE
Could you please provide assets/imagenet_label.json in generate.py? Thanks very much.

### ISSUE THREAD

**Issue by Mike001-wq** [Anima-Lab/MaskDiT#3]
I download a .json file from https://github.com/anishathalye/imagenet-simple-labels/blob/master/imagenet-simple-labels.json, which also consists of 1,000 classes. Is your imagenet_label.json in generate.py the same?

**Comment by devzhk** [comment]
Yes, they have the same order. I just upload the one I used to `assets/imagenet_label.json`
