### ISSUE TITLE
Do I need to create the docker environment to get the inception model for FID? Currently, getting file not found on detector_url.

### ISSUE THREAD

**Issue by Jollokim** [Anima-Lab/MaskDiT#6]

**Comment by devzhk** [comment]
Hi, as a quick fix, just download the inception model to your local directory from here 'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl' and then change the detector_url to your local directory.
