### ISSUE TITLE
How the get latent ImageNet dataset

### ISSUE THREAD

**Issue by liangbingzhao** [Anima-Lab/MaskDiT#7]
Do u use the `extract_imagenet_feature.py` in the U-ViT to get latent ImageNet dataset?

**Comment by 1zeryu** [comment]
I have issue for getting dataset in latent: 
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://slurm-ord.s3.amazonaws.com/datasets/imagenet_256_latent_lmdb/train/data.mdb

**Comment by liangbingzhao** [comment]
not met this issue
