### ISSUE TITLE
About training speed

### ISSUE THREAD

**Issue by liangbingzhao** [Anima-Lab/MaskDiT#8]
I test MaskDiT and DiT training on LSUNChurch dataset. But only find the training speed almost the same, but FID much worse.
Both set num_classes to 1, to imitate unconditional training. Any idea about this?

**Comment by devzhk** [comment]
Hi, num_classes should be 0 for unconditional training. Regarding the training speed, you may want to identify which part of the code is the speed bottleneck. In principle, MaskDiT processes only half tokens and thus should be faster.
